name: Deploy

on:
  push:
    branches-ignore:
      - main
      - non-encrypt

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      # === Untuk development branch ===
      - name: Update Cabang
        if: ${{ github.ref_name == 'development' }}
        run: |
          cd /var/www/html/qc/qc-payroll-cabang.goldstore.id
          git fetch origin ${{ github.ref_name }}
          git reset --hard origin/${{ github.ref_name }}

      - name: Update Qc Pusat
        if: ${{ github.ref_name == 'development' }}
        run: |
          cd /var/www/html/qc/qc-payroll.goldstore.id
          git fetch origin ${{ github.ref_name }}
          git reset --hard origin/${{ github.ref_name }}

      - name: Build Selesai
        run: echo "âœ… Build berhasil!"
